### ISSUE TITLE
Library crashes when example is run with release build configuration (Xcode 11.4)

### ISSUE THREAD

**Issue by pepejeria** [maxkonovalov/MKRingProgressView#63] opened 2020-04-06 14:28 UTC
I was seeing this issue as well with my app, but have now found an easy way to reproduce:

1. Check that you have the latest Xcode version, which currently is 11.4, earlier versions are fine
2. Download sample project
3. Edit the scheme ProgressRingExample to use the "release" build configuration (see screenshot)
4. Connect an iPhone to your computer and select that device to run the app on

This will result in a crash: GradientGenerator.swift line 113:
`let img = ctx.makeImage()!`

<img width="899" alt="Screen Shot 2020-04-06 at 16 26 07" src="https://user-images.githubusercontent.com/1394550/78569244-9cea2300-7823-11ea-9cfe-38aa4530580f.png">

**Comment by AndroidGecko** [comment] 2020-04-07 07:12
I have the same issue

**Comment by AndroidGecko** [comment] 2020-04-07 09:10
The problem is within gradients. When not using gradients e.g. 
```swift 
let useGradient = startColor != endColor
``` 
in `MKRingProgressLayer` then crash does not occur.

**Comment by AdamRedboxMobile** [comment] 2020-04-08 09:18
Setting the ring to have the same start and end colour fixed the crash for me.

**Comment by jzsoccer** [comment] 2020-04-08 17:52
Thanks for the work around. Has anyone found a way to maintain the gradient? It drastically changes the look of my app without the gradient.

**Comment by jonathanramirez** [comment] 2020-04-13 12:36
Here you have a workaround 

https://gist.github.com/jonathanramirez/d83080c61292e344d94b06672dc8fd21

<img width="571" alt="Screenshot 2020-04-13 at 12 46 31" src="https://user-images.githubusercontent.com/175867/79120797-11791080-7d94-11ea-838c-4bde0c166ab6.png">

**Comment by pepejeria** [comment] 2020-04-13 12:46
Work-around works fine for now, thanks @jonathanramirez 🥇

**Comment by pepejeria** [comment] 2020-04-17 11:33
If you use this library and want to push a new release of your app: use Xcode 11.3.1

**Comment by filipjakubowski** [comment] 2020-04-20 06:32
> If you use this library in your app and want to push a new release: use Xcode 11.3.1

It is not the best approach. I had high hopes for this but struggled with recompiling some external dependencies in older version of Swift :(

**Comment by ShMax92** [comment] 2020-04-20 17:36
Guys, confirm bug on Xcode 11.4, the same problem. And that's so disappointing :(

> If you use this library in your app and want to push a new release: use Xcode 11.3.1

Seems like an option for now.
Anyway look forward to be fixed soon.

**Comment by maxkonovalov** [comment] 2020-04-21 08:06
Hi guys! The issue was caused by compiler optimizations in Xcode 11.4 - this is now fixed in version [2.2.3](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/2.2.3) 🎉

**Closed by maxkonovalov** 2020-04-21 08:06 UTC
